name: Issue

on:
    issues:
        types: [opened, labeled]

jobs:
    issueHandler:
        name: IssueHandler
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: IssueHandler
              uses: kidonng/Scoop-GithubActions@stable
              if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
